name: ctq
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  cli_util: ^0.4.0
  ffigen: ^7.2.10
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  ffi: ^2.0.1
  path: ^1.8.3
